/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const Route2LazyImport = createFileRoute('/route2')()
const Route1LazyImport = createFileRoute('/route1')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const Route2LazyRoute = Route2LazyImport.update({
  path: '/route2',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/route2.lazy').then((d) => d.Route))

const Route1LazyRoute = Route1LazyImport.update({
  path: '/route1',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/route1.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/route1': {
      id: '/route1'
      path: '/route1'
      fullPath: '/route1'
      preLoaderRoute: typeof Route1LazyImport
      parentRoute: typeof rootRoute
    }
    '/route2': {
      id: '/route2'
      path: '/route2'
      fullPath: '/route2'
      preLoaderRoute: typeof Route2LazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  Route1LazyRoute,
  Route2LazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/route1",
        "/route2"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/route1": {
      "filePath": "route1.lazy.tsx"
    },
    "/route2": {
      "filePath": "route2.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
